# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirement.txt requirement.txt
RUN pip install --upgrade pip
RUN pip install -r requirement.txt

# Copy the rest of the application code
COPY . .

# Expose port 80 for the application
EXPOSE 80

# Run the application
CMD ["python", "app.py"]
