apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: kube-system
data:
  cloudwatch-agent-config.json: |
    {
      "agent": {
        "metrics_collection_interval": 60,
        "run_as_user": "cwagent"
      },
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/containers/*.log",
                "log_group_name": "eks-task-manager-logs",
                "log_stream_name": "{container_id}"
              }
            ]
          }
        }
      }
    }
