name: Terraform Deployment Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: Infra
        run: terraform init

      - name: Terraform Validate
        working-directory: Infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: Infra
        id: plan
        run: terraform plan -out=tfplan

      - name: Display Terraform Plan
        working-directory: Infra
        id: show-plan
        run: terraform show -no-color tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: Infra
        run: terraform destroy -auto-approve
